# Generated by Django 3.0.5 on 2020-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('sessionId', models.CharField(max_length=100)),
            ],
        ),
    ]
